services:
  frontend:
    build:
      context: ../frontend
    working_dir: /app
    ports:
      - '5173:5173' # Vite dev server
    environment:
      - NODE_ENV=development
    volumes:
      - ../frontend:/app
    command: ['npm', 'run', 'dev', '--', '--host']

  backend:
    build:
      context: ../backend
    working_dir: /code
    ports:
      - '8000:8000'
    volumes:
      - ../backend:/code
      - ../backend/spendo/wait-for-it.sh:/wait-for-it.sh
    env_file:
      - ../backend/spendo/.env
    depends_on:
      - db
    command:
      [
        'sh',
        '-c',
        'chmod +x /wait-for-it.sh && /wait-for-it.sh db 5432 python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000',
      ]

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
