services:
  frontend:
    build:
      context: ../frontend
    working_dir: /app
    ports:
      - '5173:5173' # Vite dev server
    environment:
      - NODE_ENV=development
    volumes:
      - ../frontend:/app
    command: ['npm', 'run', 'dev', '--', '--host']

  backend:
    build:
      context: ../backend
    working_dir: /code
    ports:
      - '8000:8000'
    volumes:
      - ../backend:/code
    env_file:
      - ../backend/spendo/.env
    depends_on:
      db:
        condition: service_healthy
    command:
      [
        'sh',
        '-c',
        'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000',
      ]

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spendo_user -d spendo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
